In [1]:
import numpy as np

# Creating an Array of Consecutive Numbers

In [5]:
# [0, 12)
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# [8,12)
np.arange(8,12)

array([ 8,  9, 10, 11])

In [8]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [9]:
np.arange(2,12,-2)

array([], dtype=int32)

In [10]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])