In [1]:
import numpy as np

# Reshaping

**Important**\*\*\* : The array that we are going to reshape needs to contain the same number of elements as the next array. So their size will be the same. 

In [3]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a.ndim

1

In [6]:
a.size

10

In [7]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
a.reshape(2,5).ndim

2

In [11]:
# getting an error if the number of elements does not match
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

### Detecting size with -1

In [12]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Adding new dimension

In [13]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [17]:
a[np.newaxis, :].shape

(1, 10)

In [18]:
# column vector
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [19]:
a[:, np.newaxis].shape

(10, 1)

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Or it can also be done by typing **None**

In [21]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])