In [1]:
import numpy as np

# Concatination

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
b = np.array([5, 6, 7, 8])

In [4]:
# Neither *a nor b are updated
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

* We can also concatinate pyton lists with numpy arrays

In [5]:
l = [9,10]
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
l = [9, 10, 10.4]

In [7]:
# all elements will become float
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 10.4])

In [8]:
l = [9, 10, "10.4"]

In [9]:
# all elements become string
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '10.4'],
      dtype='<U11')

* We can also concatinate pyton tuples with numpy arrays

In [10]:
l = (9,10)
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Size Mismatch

In [11]:
a

array([1, 2, 3, 4])

In [12]:
x = np.array([[1, 2, 3],
            [4, 5, 6]])

In [13]:
x.shape

(2, 3)

In [14]:
x.size

6

In [15]:
a.shape

(4,)

In [16]:
# shape mismatch
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

* To concatenate A with X, we can first reshape A to 2x2 shape and then concatenate them with axis=1.

In [17]:
a = a.reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [18]:
np.concatenate([x,a.reshape(2,2)],axis=1)

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

In [49]:
# Hackerrank Concatenate challenge

n,m,p=map(int,input().split())

lista1=[list(map(int,input().split())) for i in range(n)]
lista2=[list(map(int,input().split())) for i in range(m)]
a1=numpy.array(lista1)
a2=numpy.array(lista2)

print(numpy.concatenate((a1,a2),axis=0))

KeyboardInterrupt: Interrupted by user