In [2]:
import numpy as np

# Array Operations

In [7]:
# Operator  *  is undefined between two lists,gives error
a = [1, 2, 3]
b = [2, 4, 8]
a * b

TypeError: can't multiply sequence by non-int of type 'list'

If a list multyplied by an integer, it concatinate consecutively

In [8]:
[2, 4, 8] * 3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [6]:
[2, 4, 8] + [2, 4, 8] + [2, 4, 8]

[2, 4, 8, 2, 4, 8, 2, 4, 8]

Operator  *  is defined between two numpy arrays, multyplies element-wise

In [9]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8])

x * y

array([ 2,  8, 24])

Since it does element-wise multiplication, the number of elements must be equal.

In [10]:
x2 = np.array([1, 2, 3])
y2 = np.array([2, 4, 8, 10])

x2 * y2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [11]:
a = [1, 2, 3]
b = [2, 4, 8]

In [12]:
a + b #concatinates

[1, 2, 3, 2, 4, 8]

In [14]:
print(x)
print(y)

[1 2 3]
[2 4 8]


In [15]:
x + y

array([ 3,  6, 11])

In [16]:
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [17]:
x * 3

array([3, 6, 9])

In [18]:
x

array([1, 2, 3])

In [19]:
x = x* 3 #to update the value
x

array([3, 6, 9])