In [1]:
import numpy as np

# Array Attributes

### Shape

In [2]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
y = np.zeros((2,5,4))
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [4]:
x.shape

(2, 3)

In [5]:
y.shape

(2, 5, 4)

### ndim

In [6]:
x.ndim

2

In [7]:
y.ndim

3

### Size

In [8]:
x.size

6

In [9]:
y.size

40

### Dtype

In [10]:
x.dtype

dtype('float64')

In [11]:
y.dtype

dtype('float64')