In [1]:
import numpy as np

# Manually Specifying Array Data Type

In [9]:
x = np.array([1, 2, 3, 4.6])

In [10]:
x

array([1. , 2. , 3. , 4.6])

In [11]:
x = np.array([1, 2, 3, 4.6], dtype= "int32")

In [12]:
x

array([1, 2, 3, 4])

In [13]:
x = np.array([1, 2, 3, 4.6], dtype= "str")

In [14]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [19]:
x = np.array([1, 2, 3, 4, "5"], dtype= "int32")

In [20]:
x

array([1, 2, 3, 4, 5])