In [1]:
import numpy as np

# Any

 * To check if any element provides the requirement

In [10]:
a = np.arange(20).reshape(4,5)

In [11]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [13]:
a[a>17]

array([18, 19])

In [14]:
np.any(a>17)

True

In [15]:
np.any(a>17, axis = 0)

array([False, False, False,  True,  True])

In [16]:
np.any(a>17, axis = 1)

array([False, False, False,  True])