In [15]:
import numpy as np

# Splitting

In [16]:
l = [10, 20, 30, 40, 50, 60, 70, 80]

In [17]:
# [0,1] [2,3,4,5] [6,7]
np.split(l, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [34]:
# [0,1,2] [3,4,] [5,6,7]
np.split(l, [3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

* Caution! splitted parts are kept as array list

In [35]:
type(np.split(l, [2,6]))

list

In [39]:
type(np.split(l, [2,6]) [0])

numpy.ndarray

## Equating the result of the split to multiple variables

In [19]:
a, b = (1, 10)

In [20]:
print(a)
print(b)

1
10


In [21]:
# [0,1,2] [3,4,] [5,6,7]
x ,y, z = np.split(l, [3,5])

print(l)
print(x)
print(y)
print(z)

[10, 20, 30, 40, 50, 60, 70, 80]
[10 20 30]
[40 50]
[60 70 80]


## #vsplit

In [22]:
a = np.arange(20).reshape(2,10)

In [23]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [24]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [28]:
# first row only
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## #hsplit

In [29]:
a = np.arange(20).reshape(2,10)

In [30]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
np.hsplit(a , [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [32]:
np.hsplit(a , [2]) [0]

array([[ 0,  1],
       [10, 11]])

In [33]:
np.hsplit(a , [2]) [1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [40]:
np.hsplit(a , [2]) [0].shape

(2, 2)

In [41]:
np.hsplit(a , [2]) [1].shape

(2, 8)

In [42]:
x, y = np.hsplit(a, [2])

In [43]:
print(x)

[[ 0  1]
 [10 11]]


In [44]:
print(y)

[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [45]:
x, y, z = np.hsplit(a , [2,4])

In [46]:
print(x)

[[ 0  1]
 [10 11]]


In [47]:
print(y)

[[ 2  3]
 [12 13]]


In [48]:
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]


In [54]:
a=np.arange(20).reshape(5,4) 
print(a)

a,b,c = np.vsplit(a,[2,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [55]:
print(a)
print(b)
print(c)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]]


In [68]:
np.concatenate([a,b,c])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])