In [1]:
import numpy as np

## Creating an array whose elements are 0's 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype = str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## Creating a *Multidimentional Array* from zeros

In [4]:
# 3 rows and 4 columns array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((3, 8, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [6]:
np.zeros(2, dtype = int)

array([0, 0])

In [7]:
np.zeros((3,2), dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [8]:
np.zeros((3,2) , dtype = str)

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [10]:
np.zeros((3,2) , dtype = bool)

array([[False, False],
       [False, False],
       [False, False]])

In [38]:
def arrays(arr):
    # complete this function
    # use numpy.array
    
    arr = numpy.array(arr[::-1], dtype = float)
    return arr
    
    #or
    
    #arr = np.array(arr, float)
    #return np.flip(arr)

In [39]:
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 -2 -3 -4 5
[ 5. -4. -3. -2.  1.]
