In [1]:
import numpy as np

# Sorting

In [2]:
a = np.array([20,32,5,30,10])

In [3]:
a

array([20, 32,  5, 30, 10])

In [4]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [5]:
# updates a
a.sort() # same with  a = np.sort(a)

In [6]:
a

array([ 5, 10, 20, 30, 32])

### argsort

In [7]:
a = np.array([3, 1, 6, 5, 4, 2])

In [8]:
# Returns the indexes of the elements in ascending order
idxs = np.argsort(a)

In [9]:
idxs

array([1, 5, 0, 4, 3, 2], dtype=int64)

In [ ]:
# Hackerrank Min and Max challenge

N, M = map(int, input().split())
storage = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(storage, axis=1), axis = 0))