In [1]:
import numpy as np

# Reaching the Elements of Multideimensional Arrays

In [2]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a[0]

array([1, 2, 3, 4, 5])

In [5]:
a[1]

array([ 6,  7,  8,  9, 10])

In [10]:
a[2][3]

14

In [11]:
a[0,0]

1

In [12]:
a[1,1]

7

In [13]:
a.ndim

2

In [14]:
a[0]

array([1, 2, 3, 4, 5])

In [15]:
a[0].ndim

1

In [16]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
a[1,1] = 10

In [18]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
# It turns into whatever data type the array holds. Does not change array data type
a[1,1] = 20.40

In [20]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Slice Indexing

In [21]:
a = np.arange(1,21).reshape(4,5)

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [29]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [31]:
# Get all rows but only column in 3rd index
a[:,3]

array([ 4,  9, 14, 19])

In [38]:
a[1:3,0::4]

array([[ 6, 10],
       [11, 15]])

In [40]:
a[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])