In [1]:
import numpy as np

# Concatination

In [10]:
a = np.array([1, 2, 3, 4])

In [11]:
b = np.array([5, 6, 7, 8])

In [12]:
# Neither *a nor b are updated
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

* We can also concatinate pyton lists with numpy arrays

In [14]:
l = [9,10]
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
l = [9, 10, 10.4]

In [20]:
# all elements will become float
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '10.4'],
      dtype='<U11')

In [18]:
l = [9, 10, "10.4"]

In [21]:
# all elements become string
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '10.4'],
      dtype='<U11')

* We can also concatinate pyton tuples with numpy arrays

In [22]:
l = (9,10)
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Size Mismatch

In [23]:
a

array([1, 2, 3, 4])

In [27]:
x = np.array([[1, 2, 3],
            [4, 5, 6]])

In [28]:
x.shape

(2, 3)

In [29]:
x.size

6

In [30]:
a.shape

(4,)

In [31]:
# shape mismatch
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

* To concatenate A with X, we can first reshape A to 2x2 shape and then concatenate them with axis=1.

In [45]:
a = a.reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [43]:
np.concatenate([x,a.reshape(2,2)],axis=1)

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])