In [1]:
import numpy as np

# Subarray

In [7]:
a = np.arange(1,21).reshape(4,5)

In [8]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
b = a[:2,:3]

In [10]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [11]:
b.ndim

2

In [12]:
b[0,0] = 100

In [13]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [14]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

# Copy

* If we use the copy() method, any change of value in the subarray does not affect the original array.

In [15]:
a = np.arange(1,21).reshape(4,5)

In [16]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
b = a[:2,:3].copy()

In [18]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [20]:
b[0,0] = 100

In [21]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])