In [1]:
import numpy as np

# Conditional Indexing

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [5]:
a[a<5]

array([1, 2, 3, 4])

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
filt = a<3

In [8]:
a[filt]

array([1, 2])

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [11]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [12]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [13]:
a[a==b]

array([3, 4, 5, 7, 8])

In [14]:
b[a==b]

array([3, 4, 5, 7, 8])

In [15]:
# broadcasting
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [16]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [18]:
# We cannot use the logic that we normally set up with **and** **or** operators with numpy.
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [19]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [20]:
a[(a < 3) | (a > 5)]

array([1, 2, 6, 7, 8, 9])

In [26]:
filt = (a < 3) | (a > 5)

In [27]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [28]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [29]:
a[(a > 3) & (a <= 5)]

array([4, 5])

## Negation of Filter


In [30]:
a = np.arange(1,21).reshape(4,5)

In [41]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
filt = a < 5

In [43]:
a[filt]

array([1, 2, 3, 4])

In [46]:
filt = (a>5) & (a<9)

In [45]:
a[(a>5) & (a<9)]

array([6, 7, 8])

In [50]:
filt

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [51]:
~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [48]:
filt = ~((a>5) & (a<9))

In [49]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Conditional Indexing in Multidimensional Arrays

In [52]:
a = np.arange(1,21).reshape(4,5)

In [53]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [54]:
type(a)

numpy.ndarray

In [55]:
type(a<7)

numpy.ndarray

In [56]:
a<7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [57]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [58]:
a[a<7].shape

(6,)

In [64]:
a = np.array([1,2,3,None])

In [65]:
a

array([1, 2, 3, None], dtype=object)

In [66]:
a==None

array([False, False, False,  True])

In [67]:
a[a==None]

array([None], dtype=object)

In [70]:
a=np.arange(-5,3).reshape(2,4)
a[(a<0)|(a==2)]

array([-5, -4, -3, -2, -1,  2])