In [1]:
import numpy as np

# Sum

* 
Let's find how many elements provide the given contiion

In [30]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
np.sum(a)

210

In [5]:
filt = a<5

In [10]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [9]:
np.sum(filt)

4

In [11]:
a[filt]

array([1, 2, 3, 4])

In [7]:
np.sum(a[filt])

10

In [13]:
filt = (a>5) & (a<9)

In [14]:
np.sum(filt)

3

In [15]:
np.sum(a[filt])

21

In [16]:
filt = ~((a>5) & (a<9))

In [18]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
np.sum(a[filt])

189

In [39]:
np.sum(~((a>5) & (a<9)))

17

In [38]:
np.sum(a[~((a>5) & (a<9))])

189

## Summation on Specific Axis

In [40]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [42]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])

In [45]:
a=np.arange(1,21).reshape(4,5) 
np.sum(a,axis=0).shape


(5,)

In [ ]:
import numpy

N, M = map(int, input().split())
array = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(array, axis=0)))